In [2]:
import requests
import pandas as pd
import time

API_KEY = "579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007"

RESOURCE_ID = "9ef84268-d588-465a-a308-a864a43d0070"

BASE_URL = f"https://api.data.gov.in/resource/{RESOURCE_ID}"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
}

all_records = []

offset = 0
limit = 1000

while True:

    params = {
        "api-key": API_KEY,
        "format": "json",
        "offset": offset,
        "limit": limit
    }

    try:
        response = requests.get(
            BASE_URL,
            params=params,
            headers=headers,
            timeout=60
        )

        print(response.url)
        print(response.status_code)

        response.raise_for_status()

        data = response.json()

        records = data.get("records", [])

        if not records:
            print("Finished.")
            break

        all_records.extend(records)

        print(f"Total downloaded: {len(all_records)}")

        offset += limit

        time.sleep(2)

    except Exception as e:
        print(e)
        break

df = pd.DataFrame(all_records)

df.to_csv("AGMARKNET.csv", index=False)

print(df.shape)

https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=0&limit=1000
200
Total downloaded: 1000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=1000&limit=1000
200
Total downloaded: 2000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=2000&limit=1000
200
Total downloaded: 3000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=3000&limit=1000
200
Total downloaded: 4000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=4000&limit=1000
200
Total downloaded: 5000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=5000&limit=1000
200
Total downloaded: 6000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=6000&limit=1000
200
Total downloaded: 7000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=7000&limit=1000
200
Total downloaded: 8000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=8000&limit=1000
200
Total downloaded: 9000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=9000&limit=1000
200
Total downloaded: 10000
https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001a910e05595ff4b6259891847cfb6a007&format=json&offset=10000&limit=1000
200
Finished.
(10000, 10)

In [8]:
import pandas as pd

df = pd.read_csv("AGMARKNET.csv")

In [9]:
df.head()

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price
0,Odisha,Sambalpur,Sahaspur APMC,Little gourd(Kundru),Other,Local,13/07/2026,1600.0,2000.0,1800.0
1,Odisha,Mayurbhanja,Baripada APMC,Ridgeguard(Tori),Ridgeguard(Tori),Local,13/07/2026,4000.0,5000.0,4500.0
2,Keralam,Kozhikode(Calicut),Mukkom Market,Apple,Other,Large,13/07/2026,26000.0,27000.0,26500.0
3,Keralam,Kozhikode(Calicut),Mukkom Market,Bitter gourd,Bitter Gourd,FAQ,13/07/2026,6000.0,6400.0,6200.0
4,Keralam,Kozhikode(Calicut),Mukkom Market,Carrot,Carrot,FAQ,13/07/2026,6000.0,6500.0,6200.0

In [10]:
df.shape

(10000, 10)

In [11]:
df['arrival_date'].nunique()

1

In [12]:
print(df['arrival_date'].min())
print(df['arrival_date'].max())

13/07/2026
13/07/2026

In [14]:
print(df.shape)

(10000, 10)

In [16]:
print(df.isnull().sum())

state           0
district        0
market          0
commodity       0
variety         0
grade           0
arrival_date    0
min_price       0
max_price       0
modal_price     0
dtype: int64

In [17]:
print(df.duplicated().sum())

print(df[['state','district','market']].drop_duplicates().shape)

949
(1391, 3)

In [18]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(
    ["market", "commodity"]
).head(20)

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price
7580,Maharashtra,Nandurbar,APMC Nandurbar,Jowar(Sorghum),Other,Local,13/07/2026,1850.0,2400.0,2125.0
8341,Maharashtra,Nandurbar,APMC Nandurbar,Jowar(Sorghum),Other,Local,13/07/2026,1850.0,2400.0,2125.0
7510,Maharashtra,Jalgaon,APMC PACHORA,Wheat,Other,Non-FAQ,13/07/2026,1991.0,2484.0,2200.0
8271,Maharashtra,Jalgaon,APMC PACHORA,Wheat,Other,Non-FAQ,13/07/2026,1991.0,2484.0,2200.0
8035,Karnataka,Shivamogga,APMC THIRTHAHALLI,Arecanut(Betelnut/Supari),Rashi,Local,13/07/2026,43335.0,43335.0,43335.0
9262,Karnataka,Shivamogga,APMC THIRTHAHALLI,Arecanut(Betelnut/Supari),Rashi,Local,13/07/2026,43335.0,43335.0,43335.0
7594,Uttar Pradesh,Agra,Achnera APMC,Potato,Other,FAQ,13/07/2026,550.0,550.0,550.0
8355,Uttar Pradesh,Agra,Achnera APMC,Potato,Other,FAQ,13/07/2026,550.0,550.0,550.0
7601,Uttar Pradesh,Mirzapur,Ahirora APMC,Cauliflower,Cauliflower,Medium,13/07/2026,2000.0,2200.0,2100.0
8362,Uttar Pradesh,Mirzapur,Ahirora APMC,Cauliflower,Cauliflower,Medium,13/07/2026,2000.0,2200.0,2100.0
7600,Uttar Pradesh,Mirzapur,Ahirora APMC,Pointed gourd(Parval),Pointed gourd (Parval),Medium,13/07/2026,3500.0,4000.0,4000.0
8361,Uttar Pradesh,Mirzapur,Ahirora APMC,Pointed gourd(Parval),Pointed gourd (Parval),Medium,13/07/2026,3500.0,4000.0,4000.0
7602,Uttar Pradesh,Mirzapur,Ahirora APMC,Raddish,Raddish,Medium,13/07/2026,900.0,1000.0,1000.0
8363,Uttar Pradesh,Mirzapur,Ahirora APMC,Raddish,Raddish,Medium,13/07/2026,900.0,1000.0,1000.0
6652,Gujarat,Ahmedabad,Ahmedabad(Chimanbhai Patal Market Vasana) APMC,Onion,Other,FAQ,13/07/2026,2000.0,2500.0,2350.0
8631,Gujarat,Ahmedabad,Ahmedabad(Chimanbhai Patal Market Vasana) APMC,Onion,Other,FAQ,13/07/2026,2000.0,2500.0,2350.0
7512,Maharashtra,Latur,Ahmedpur APMC,Groundnut,Other,FAQ,13/07/2026,7500.0,8500.0,8017.0
8273,Maharashtra,Latur,Ahmedpur APMC,Groundnut,Other,FAQ,13/07/2026,7500.0,8500.0,8017.0
7511,Maharashtra,Latur,Ahmedpur APMC,Jowar(Sorghum),Other,FAQ,13/07/2026,3699.0,3700.0,3699.0
8272,Maharashtra,Latur,Ahmedpur APMC,Jowar(Sorghum),Other,FAQ,13/07/2026,3699.0,3700.0,3699.0

In [19]:
df = df.drop_duplicates().reset_index(drop=True)

In [20]:
print(df.shape)

print(df.duplicated().sum())

(9051, 10)
0

In [21]:
df.isnull().sum()

state           0
district        0
market          0
commodity       0
variety         0
grade           0
arrival_date    0
min_price       0
max_price       0
modal_price     0
dtype: int64

In [22]:
df.dtypes

state            object
district         object
market           object
commodity        object
variety          object
grade            object
arrival_date     object
min_price       float64
max_price       float64
modal_price     float64
dtype: object

In [23]:
invalid = df[
    (df["min_price"] > df["modal_price"]) |
    (df["modal_price"] > df["max_price"])
]

print(invalid.shape)

(2, 10)

In [24]:
(df[["min_price","max_price","modal_price"]] < 0).sum()

min_price      0
max_price      0
modal_price    0
dtype: int64

In [25]:
print(df.shape)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.dtypes)

(9051, 10)
state           0
district        0
market          0
commodity       0
variety         0
grade           0
arrival_date    0
min_price       0
max_price       0
modal_price     0
dtype: int64
0
state            object
district         object
market           object
commodity        object
variety          object
grade            object
arrival_date     object
min_price       float64
max_price       float64
modal_price     float64
dtype: object

In [26]:
invalid[[
    "state",
    "district",
    "market",
    "commodity",
    "min_price",
    "modal_price",
    "max_price"
]]

,state,district,market,commodity,min_price,modal_price,max_price
1196,Karnataka,Bengaluru South,Channapatna APMC,Ridgeguard(Tori),2600.0,2000.0,3200.0
4044,Karnataka,Bellary,Ballari APMC,Maize,2401.0,2365.0,2626.0

In [27]:
df = df.drop(invalid.index).reset_index(drop=True)

In [28]:
invalid = df[
    (df["min_price"] > df["modal_price"]) |
    (df["modal_price"] > df["max_price"])
]

print(invalid.shape)

(0, 10)

In [29]:
# Save cleaned Dataset 1
df.to_csv("Dataset1_Cleaned_AGMARKNET.csv", index=False)

print("Dataset 1 saved successfully!")

Dataset 1 saved successfully!